<?php

namespace Database\Seeders;

use App\Models\ClubResource;
use Illuminate\Database\Seeder;

class ClubPortalSeeder extends Seeder
{
    public function run(): void
    {
        $resources = [
            [
                'title' => 'SLAU Internal Red Team Sprint',
                'slug' => 'slau-internal-red-team-sprint',
                'category' => 'competition',
                'platform' => 'Internal',
                'difficulty' => 'Intermediate',
                'status' => 'open',
                'location' => 'Cyber Lab',
                'cta_label' => 'View competition brief',
                'external_url' => 'https://attendance.maticent.com/#home',
                'summary' => 'A timed internal offensive security challenge built around reconnaissance, exploitation, and reporting discipline.',
                'details' => 'Members work in teams, submit findings, and are scored on methodology, impact, and communication.',
                'target_total' => 4,
                'points' => 120,
                'starts_at' => now()->addDays(4),
                'ends_at' => now()->addDays(11),
                'sort_order' => 1,
            ],
            [
                'title' => 'Campus Blue Team Readiness Drill',
                'slug' => 'campus-blue-team-readiness-drill',
                'category' => 'competition',
                'platform' => 'Internal',
                'difficulty' => 'Beginner',
                'status' => 'scheduled',
                'location' => 'Hybrid',
                'cta_label' => 'Prepare for drill',
                'external_url' => 'https://attendance.maticent.com/#home',
                'summary' => 'A defensive practice cycle focused on alert review, triage workflow, and incident reporting habits.',
                'details' => 'Ideal for members growing from event participation into practical security operations.',
                'target_total' => 3,
                'points' => 90,
                'starts_at' => now()->addDays(12),
                'ends_at' => now()->addDays(18),
                'sort_order' => 2,
            ],
            [
                'title' => '2026 Cabinet Voting Briefing',
                'slug' => '2026-cabinet-voting-briefing',
                'category' => 'voting',
                'platform' => 'Internal',
                'difficulty' => 'Member Access',
                'status' => 'scheduled',
                'location' => 'Members Portal',
                'cta_label' => 'Open voting guide',
                'external_url' => '#',
                'summary' => 'Review the election calendar, candidate expectations, and voting instructions for the upcoming cabinet cycle.',
                'details' => 'This section prepares members for cabinet voting and will later host direct election access once enabled.',
                'target_total' => 1,
                'points' => 20,
                'starts_at' => now()->addDays(7),
                'ends_at' => now()->addDays(21),
                'sort_order' => 3,
            ],
            [
                'title' => 'Hack The Box Academy Track',
                'slug' => 'hack-the-box-academy-track',
                'category' => 'ctf',
                'platform' => 'Hack The Box',
                'difficulty' => 'Intermediate',
                'status' => 'open',
                'location' => 'Online',
                'cta_label' => 'Launch HTB',
                'external_url' => 'https://academy.hackthebox.com/',
                'summary' => 'Structured hands-on challenge path for enumeration, web exploitation, Linux fundamentals, and privilege escalation.',
                'details' => 'Members can track rooms completed, score, and notes while following the club progression path.',
                'target_total' => 12,
                'points' => 150,
                'starts_at' => now(),
                'ends_at' => now()->addMonths(3),
                'sort_order' => 4,
            ],
            [
                'title' => 'PicoCTF Practice Sprint',
                'slug' => 'picoctf-practice-sprint',
                'category' => 'ctf',
                'platform' => 'PicoCTF',
                'difficulty' => 'Beginner',
                'status' => 'open',
                'location' => 'Online',
                'cta_label' => 'Launch PicoCTF',
                'external_url' => 'https://play.picoctf.org/',
                'summary' => 'A beginner-friendly challenge sprint for crypto, web, binary, and forensic problem solving.',
                'details' => 'Good for early members who need consistent challenge practice before internal competitions.',
                'target_total' => 15,
                'points' => 130,
                'starts_at' => now(),
                'ends_at' => now()->addMonths(2),
                'sort_order' => 5,
            ],
            [
                'title' => 'Internal Web Exploitation Labs',
                'slug' => 'internal-web-exploitation-labs',
                'category' => 'ctf',
                'platform' => 'SLAU Lab',
                'difficulty' => 'Intermediate',
                'status' => 'active',
                'location' => 'Cyber Lab',
                'cta_label' => 'Open lab notes',
                'external_url' => '#',
                'summary' => 'A club-maintained set of practical exercises aligned to common web application security weaknesses.',
                'details' => 'Members work through lab modules and record milestones directly in the club portal.',
                'target_total' => 8,
                'points' => 140,
                'starts_at' => now(),
                'ends_at' => now()->addMonths(1),
                'sort_order' => 6,
            ],
            [
                'title' => 'Secure Web Development Class',
                'slug' => 'secure-web-development-class',
                'category' => 'class',
                'platform' => 'Google Meet',
                'difficulty' => 'Beginner',
                'status' => 'active',
                'location' => 'Online',
                'cta_label' => 'Join class link',
                'external_url' => 'https://meet.google.com/',
                'summary' => 'Weekly secure coding class covering input validation, authentication design, and deployment safety.',
                'details' => 'Members use this class as a foundation before moving into advanced project work.',
                'target_total' => 6,
                'points' => 100,
                'starts_at' => now(),
                'ends_at' => now()->addWeeks(6),
                'sort_order' => 7,
            ],
            [
                'title' => 'Digital Forensics Case Review',
                'slug' => 'digital-forensics-case-review',
                'category' => 'class',
                'platform' => 'Zoom',
                'difficulty' => 'Intermediate',
                'status' => 'scheduled',
                'location' => 'Online',
                'cta_label' => 'Review class plan',
                'external_url' => 'https://zoom.us/',
                'summary' => 'An internal study series on evidence handling, timelines, and investigative note-taking.',
                'details' => 'Best suited for members exploring forensic analysis and structured investigation.',
                'target_total' => 5,
                'points' => 95,
                'starts_at' => now()->addDays(9),
                'ends_at' => now()->addWeeks(7),
                'sort_order' => 8,
            ],
        ];

        foreach ($resources as $resource) {
            ClubResource::query()->updateOrCreate(
                ['slug' => $resource['slug']],
                $resource,
            );
        }
    }
}
