<table>
    <tr>
        <td colspan="4" style="font-size: 16px; font-weight: bold; text-align: center;">
            Financial Statement Report
        </td>
    </tr>
    <tr>
        <td colspan="4" style="text-align: center;">
            Generated: {{ now()->format('F d, Y \a\t h:i A') }}
        </td>
    </tr>
    <tr>
        <td colspan="4" style="text-align: center;">
            Period: {{ $startDate->format('F d, Y') }} - {{ $endDate->format('F d, Y') }}
        </td>
    </tr>
    <tr>
        <td colspan="4" style="text-align: center;">
            Report Type: {{ ucfirst($reportType) }}
        </td>
    </tr>
    <tr><td colspan="4"></td></tr>

    <!-- Summary -->
    <tr>
        <td colspan="4" style="font-weight: bold; background-color: #f0f0f0;">SUMMARY</td>
    </tr>
    <tr style="font-weight: bold;">
        <td>Metric</td>
        <td>Value</td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Total Income</td>
        <td>${{ number_format((float)($data['totalIncome'] ?? 0), 2) }}</td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Total Expenses</td>
        <td>${{ number_format($data['totalExpenses'] ?? 0, 2) }}</td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Net Income</td>
        <td style="color: {{ ($data['netIncome'] ?? 0) >= 0 ? '#00a65a' : '#dd4b39' }};">
            ${{ number_format($data['netIncome'] ?? 0, 2) }}
        </td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Total Transactions</td>
        <td>{{ number_format($data['transactionCount'] ?? 0) }}</td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Average Transaction</td>
        <td>${{ number_format($data['averageTransaction'] ?? 0, 2) }}</td>
        <td></td>
        <td></td>
    </tr>
    <tr><td colspan="4"></td></tr>

    <!-- Income Breakdown -->
    <tr>
        <td colspan="4" style="font-weight: bold; background-color: #f0f0f0;">INCOME BREAKDOWN</td>
    </tr>
    <tr style="font-weight: bold;">
        <td>Category</td>
        <td>Transaction Count</td>
        <td>Amount</td>
        <td>Percentage</td>
    </tr>
    @foreach(($data['incomeByCategory'] ?? []) as $category)
    <tr>
        <td>{{ $category['category'] ?? $category->category ?? '' }}</td>
        <td>{{ $category['count'] ?? $category->count ?? 0 }}</td>
        <td>${{ number_format($category['total'] ?? $category->total ?? 0, 2) }}</td>
        <td>
            @php
                $percentage = ($data['totalIncome'] ?? 0) > 0
                    ? (($category['total'] ?? $category->total ?? 0) / $data['totalIncome']) * 100
                    : 0;
            @endphp
            {{ number_format($percentage, 1) }}%
        </td>
    </tr>
    @endforeach
    <tr style="font-weight: bold;">
        <td>Total Income</td>
        <td>{{ collect($data['incomeByCategory'] ?? [])->sum('count') }}</td>
        <td>${{ number_format($data['totalIncome'] ?? 0, 2) }}</td>
        <td>100%</td>
    </tr>
    <tr><td colspan="4"></td></tr>

    <!-- Expense Breakdown -->
    <tr>
        <td colspan="4" style="font-weight: bold; background-color: #f0f0f0;">EXPENSE BREAKDOWN</td>
    </tr>
    <tr style="font-weight: bold;">
        <td>Category</td>
        <td>Transaction Count</td>
        <td>Amount</td>
        <td>Percentage</td>
    </tr>
    @foreach(($data['expensesByCategory'] ?? []) as $category)
    <tr>
        <td>{{ $category['category'] ?? $category->category ?? '' }}</td>
        <td>{{ $category['count'] ?? $category->count ?? 0 }}</td>
        <td>${{ number_format($category['total'] ?? $category->total ?? 0, 2) }}</td>
        <td>
            @php
                $percentage = ($data['totalExpenses'] ?? 0) > 0
                    ? (($category['total'] ?? $category->total ?? 0) / $data['totalExpenses']) * 100
                    : 0;
            @endphp
            {{ number_format($percentage, 1) }}%
        </td>
    </tr>
    @endforeach
    <tr style="font-weight: bold;">
        <td>Total Expenses</td>
        <td>{{ collect($data['expensesByCategory'] ?? [])->sum('count') }}</td>
        <td>${{ number_format($data['totalExpenses'] ?? 0, 2) }}</td>
        <td>100%</td>
    </tr>

    <!-- Footer -->
    <tr><td colspan="4"></td></tr>
    <tr>
        <td colspan="4" style="font-size: 10px; color: #666;">
            Report generated by: {{ auth()->user()->name ?? 'System' }}<br>
            Generated on: {{ now()->format('Y-m-d H:i:s') }}<br>
            Confidential - For internal use only
        </td>
    </tr>
</table>
