<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Financial Statement Report</title>
    <style>
        /* Simple styles - no fancy characters */
        body {
            font-family: Arial, sans-serif;
            font-size: 11pt;
            line-height: 1.4;
            color: #000000;
        }
        h1 {
            color: #000000;
            text-align: center;
            margin-bottom: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #000000;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f0f0f0;
            font-weight: bold;
        }
        .summary {
            margin: 20px 0;
            padding: 15px;
            border: 1px solid #000000;
        }
        .positive {
            color: #006600;
        }
        .negative {
            color: #cc0000;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Financial Statement Report</h1>
        <p><strong>Generated:</strong> {{ htmlspecialchars(now()->format('F d, Y \\a\\t h:i A'), ENT_QUOTES, 'UTF-8') }}</p>
        <p><strong>Period:</strong> {{ htmlspecialchars($startDate->format('F d, Y'), ENT_QUOTES, 'UTF-8') }} - {{ htmlspecialchars($endDate->format('F d, Y'), ENT_QUOTES, 'UTF-8') }}</p>
        <p><strong>Report Type:</strong> {{ htmlspecialchars(ucfirst($reportType), ENT_QUOTES, 'UTF-8') }}</p>
    </div>

    <!-- Summary Section -->
    <div class="summary">
        <h2>Summary</h2>
        <table>
            <tr>
                <td><strong>Total Income:</strong></td>
                <td>${{ htmlspecialchars(number_format($data['totalIncome'] ?? 0, 2), ENT_QUOTES, 'UTF-8') }}</td>
            </tr>
            <tr>
                <td><strong>Total Expenses:</strong></td>
                <td>${{ htmlspecialchars(number_format($data['totalExpenses'] ?? 0, 2), ENT_QUOTES, 'UTF-8') }}</td>
            </tr>
            <tr>
                <td><strong>Net Income:</strong></td>
                <td class="{{ ($data['netIncome'] ?? 0) >= 0 ? 'positive' : 'negative' }}">
                    ${{ htmlspecialchars(number_format($data['netIncome'] ?? 0, 2), ENT_QUOTES, 'UTF-8') }}
                </td>
            </tr>
            <tr>
                <td><strong>Total Transactions:</strong></td>
                <td>{{ htmlspecialchars(number_format($data['transactionCount'] ?? 0), ENT_QUOTES, 'UTF-8') }}</td>
            </tr>
        </table>
    </div>

    <!-- Simple Data Display -->
    <h2>Transaction Summary</h2>
    <table>
        <tr>
            <th>Metric</th>
            <th>Value</th>
        </tr>
        <tr>
            <td>Total Income</td>
            <td>${{ htmlspecialchars(number_format($data['totalIncome'] ?? 0, 2), ENT_QUOTES, 'UTF-8') }}</td>
        </tr>
        <tr>
            <td>Total Expenses</td>
            <td>${{ htmlspecialchars(number_format($data['totalExpenses'] ?? 0, 2), ENT_QUOTES, 'UTF-8') }}</td>
        </tr>
        <tr>
            <td>Net Profit/Loss</td>
            <td>${{ htmlspecialchars(number_format($data['netIncome'] ?? 0, 2), ENT_QUOTES, 'UTF-8') }}</td>
        </tr>
    </table>

    <!-- Footer -->
    <div style="margin-top: 50px; padding-top: 20px; border-top: 1px solid #000; font-size: 9pt;">
        <p>Report generated by: {{ htmlspecialchars(auth()->user()->name ?? 'System', ENT_QUOTES, 'UTF-8') }}</p>
        <p>Generated on: {{ htmlspecialchars(now()->format('Y-m-d H:i:s'), ENT_QUOTES, 'UTF-8') }}</p>
        <p>Confidential - For internal use only</p>
    </div>
</body>
</html>
